---
- name: Install melodi
  hosts: dev

  tasks:
  - name: install prerequisites
    dnf:
      name:
      - wget
      - vim
      - git
      state: present

  - name: install apache
    dnf:
      name: httpd
      state: present

  - name: start httpd
    systemd:
      name: httpd
      state: started
      enabled: yes

  - name: Recursively remove directory
    ansible.builtin.file:
      path: /var/www/html/melodi
      state: absent

  - name: recursively change ownership of a directory
    file:
      path: /var/www/html
      state: directory
      recurse: yes
      owner: apache
      group: apache
